# Generalized Subspace Model

In [1]:
# Add "beer" to the PYTHONPATH
import sys
sys.path.insert(0, '../')

import math
import copy

import beer
import numpy as np
import torch

# For plotting.
from bokeh.io import show, output_notebook
from bokeh.plotting import figure, gridplot
from bokeh.models import LinearAxis, Range1d
from bokeh.palettes import Category10 as palette
output_notebook()

# Convenience functions for plotting.
import plotting

%load_ext autoreload
%autoreload 2

Loading BokehJS ...

## Synthetic Data

In [2]:
def generate_data(global_mean, angle, size, weight):
    rotation = np.array([
        [math.cos(angle), -math.sin(angle)],
        [math.sin(angle), math.cos(angle)]
    ])
    
    scale = np.array([.5, 2.])
    init_cov = np.diag(scale**2)
    cov1 = rotation.T @ init_cov @ rotation
    cov2 = rotation @ init_cov @ rotation.T
    mean1 = global_mean + np.array([0, 2])
    mean2 = global_mean - np.array([0, 2])
    data1 = (scale * np.random.randn(int(size * weight), 2)) @ rotation + mean1
    data2 = (scale * np.random.randn(int(size * (1 - weight)), 2)) @ rotation.T + mean2
    data = np.vstack([data1, data2])
    np.random.shuffle(data)
    return data, (mean1, mean2), (cov1, cov2), (weight, 1-weight)

datasets = []
means = []
covs = []
weights = []
start_angle = -.5 * math.pi
boundary = 50
nmodels = 10
for h in np.linspace(-boundary, boundary, nmodels):
    mean = np.array([1, 0]) * h
    angle = start_angle + (h + boundary) * (math.pi) / (2 * boundary) 
    ratio = (h + boundary) / (2 * boundary)
    ratio = .1 + .8 * ratio
    data, m_means, m_covs, m_weights = generate_data(mean, angle, size=100, weight=ratio)
    datasets.append(data)
    means.append(m_means)
    covs.append(m_covs)
    weights.append(m_weights)
data = np.vstack(datasets)

# Convert the data to pytorch tensor to work with beer.  
datasets = [torch.from_numpy(data) for data in datasets]

# Colors 
colors = palette[10]

fig = figure(width=400, height=400)
for color, dataset, m_means, m_covs, m_weights in zip(colors, datasets, means, covs, weights):
    dataset = dataset.numpy()
    plotting.plot_normal(fig, m_means[0], m_covs[0], alpha=.7 * m_weights[0], color=color)
    plotting.plot_normal(fig, m_means[1], m_covs[1], alpha=.7 * m_weights[1], color=color)
    fig.circle(dataset[:, 0], dataset[:, 1], color=color)
show(fig)

## Generalized Subspace Model

### Creating the GSM

The GSM is composed of a latent prior, an affine transformation, a generic subspace model which indicates how to transform the projections of the embedding into a concrete model and the instances of the generic subspace model (paired with latent posterior distributions, one for each subspace model instance).

In [3]:
obs_dim = 2
latent_dim = 2

# Type of covariance for the Subspace GMMs.
cov_type = 'full' # full/diagonal/isotropic
 
# Prior over the latent space.
latent_prior = beer.Normal.create(
    torch.zeros(latent_dim), 
    torch.ones(latent_dim)
).double()

# Data model (SGMM).
modelset = beer.NormalSet.create(
    mean=torch.zeros(obs_dim), cov=torch.ones(obs_dim),
    size=2,
    cov_type=cov_type
)
sgmm = beer.Mixture.create(modelset).double()

# We specify which parameters will be handled by the
# subspace in the GMM. 
newparams = {
    param: beer.SubspaceBayesianParameter.from_parameter(param, latent_prior)
    for param in sgmm.bayesian_parameters()
}
sgmm.replace_parameters(newparams)

# Create the Generalized Subspace Model
gsm = beer.GSM.create(sgmm, latent_dim, latent_prior, prior_strength=1e-6).double()

# Create the instance of SGMM for each dataset
sgmms, latent_posts = gsm.new_models(len(datasets))

print('Latent prior')
print('============')
print(latent_prior)    
print()

print('Subspace GMM (generic model)')
print('============================')
print(sgmm)    
print()

print('Generalized Subspace Model')
print('==========================')
print(gsm) 
print()

print('Subspace GMMs (concrete instances)')
print('==================================')
print('(1) -', sgmms[0])   
print()
print('...')
print()
print(f'({len(datasets)}) -', sgmms[-1])
print()

Latent prior
Normal(
  (mean_precision): ConjugateBayesianParameter(prior=NormalWishart, posterior=NormalWishart)
)

Subspace GMM (generic model)
Mixture(
  (modelset): NormalSet(
    (means_precisions): SubspaceBayesianParameter(prior=Normal, posterior=<unspecified>)
  )
  (weights): SubspaceBayesianParameter(prior=Normal, posterior=<unspecified>)
)

Generalized Subspace Model
GSM(
  (model): Mixture(
    (modelset): NormalSet(
      (means_precisions): SubspaceBayesianParameter(prior=Normal, posterior=<unspecified>)
    )
    (weights): SubspaceBayesianParameter(prior=Normal, posterior=<unspecified>)
  )
  (affine_transform): AffineTransform(
    (weights): NonConjugateBayesianParameter(prior=NormalDiagonalCovariance, posterior=NormalDiagonalCovariance)
    (bias): NonConjugateBayesianParameter(prior=NormalDiagonalCovariance, posterior=NormalDiagonalCovariance)
  )
  (latent_prior): Normal(
    (mean_precision): ConjugateBayesianParameter(prior=NormalWishart, posterior=NormalWishart)

### Pre-training

Before to start the training we need to inialize the subspace. To do so, we first train a Normal distribution for each dataset and we'll use its statistics as initial statistics for all the Normal distributions of the SGMMs. 

In [4]:
def create_normal(dataset, cov_type):
    data_mean = dataset.mean(dim=0)
    data_var = dataset.var(dim=0)
    return beer.Normal.create(data_mean, data_var, cov_type=cov_type).double()

def fit_normal(normal, dataset, epochs=100):
    optim = beer.VariationalBayesOptimizer(normal.mean_field_factorization(), lrate=1.)
    for epoch in range(epochs):
        optim.init_step()
        elbo = beer.evidence_lower_bound(normal, dataset)
        elbo.backward()
        optim.step()
        
normals = [create_normal(dataset, cov_type=cov_type) for dataset in datasets]
for normal, dataset in zip(normals, datasets):
    fit_normal(normal, dataset)
    
fig = figure(width=400, height=400)
for normal, dataset, color in zip(normals, datasets, colors):
    dataset = dataset.numpy()
    mean = normal.mean.numpy()
    cov = normal.cov.numpy()
    plotting.plot_normal(fig, mean, cov, alpha=.5, color=color)
    fig.circle(dataset[:, 0], dataset[:, 1], color=color, alpha=.1)
    
show(fig)

In [5]:
# Prepare the initial weights sufficient statistics.
ncomp = len(sgmm.modelset)
weights_stats = torch.zeros(len(datasets), ncomp).double()
counts = torch.cat([torch.tensor(float(len(dataset))).view(1) for dataset in datasets]).double()
weights_stats[:] = counts[:, None] / ncomp
weights_stats[:, -1] = counts
weights_stats

# Prepare the initial sufficient statistics for the 
# components of the GMM.
normals_stats =  [normal.mean_precision.stats.repeat(ncomp, 1)
                  for normal in normals]
for i, gmm in enumerate(sgmms):
    gmm.weights.stats = weights_stats[i]
    gmm.modelset.means_precisions.stats = normals_stats[i]
    
# NOTE: we initialize the stats of all the parameters
# whether they are included in the subspace or not.
# For parameters that are not included in the subspace,
# this initialization will be discarded during
# the training ("optim.init_step()" clear the stats).

In [6]:
epochs = 15_000
lrate_cjg = 1e-1
lrate_std = 1e-1
params = list(latent_posts.parameters()) + list(gsm.parameters())
std_optim = torch.optim.Adam(params, lr=lrate_std)
optim = beer.VariationalBayesOptimizer([[]], lrate=lrate_cjg, std_optim=std_optim)

elbos = []
for epoch in range(1, epochs + 1): 
    optim.init_step()
    elbo = beer.evidence_lower_bound(gsm, sgmms, latent_posts=latent_posts, 
                                     latent_nsamples=5, params_nsamples=5)
    elbo.backward()
    optim.step()
    elbos.append(float(elbo))

In [7]:
fig = figure()
fig.line(range(len(elbos)), elbos)
show(fig)

In [8]:
fig = figure(title='Subspace GMM')
for gmm, dataset, color in zip(sgmms, datasets, colors):
    dataset = dataset.numpy()
    plotting.plot_gmm(fig, gmm, alpha=.5, color=color)
    fig.circle(dataset[:, 0], dataset[:, 1], color=color, alpha=.1)
show(fig)

### Training

Now the GSM is initialized so we start the "actual" training by updating the statistics of the parameters whenever the GSM is updated.

In [9]:
epochs = 5_000

# This function accumulate the statistics for the parameters
# of the subspace and update the parameters that are not
# part of the subspace.
def accumulate_stats(models, datasets, optims):
    for model, X, optim in zip(models, datasets, optims):
        optim.init_step()
        elbo = beer.evidence_lower_bound(model, X) 
        elbo.backward(std_params=False)
        optim.step()
        
# Prepare an optimzer for each SGMM. The optimizer
# will handle all parameters that are note included
# in the subspace.
sgmms_optims = []
for gmm in sgmms:
    mf_groups = []
    for group in gmm.mean_field_factorization():
        new_group = []
        for param in group:
            if isinstance(param, beer.ConjugateBayesianParameter):
                new_group.append(param)
        mf_groups.append(new_group)
    optim = beer.VariationalBayesOptimizer(mf_groups, lrate=1.)
    sgmms_optims.append(optim)
    
# We create a new optimizer for the GSM that will update the 
# latent prior as well.
optim = beer.VariationalBayesOptimizer(gsm.latent_prior.mean_field_factorization(), lrate=1e-1, std_optim=std_optim)


elbos = []
for epoch in range(1, epochs + 1): 
    accumulate_stats(sgmms, datasets, sgmms_optims)
    optim.init_step()
    elbo = beer.evidence_lower_bound(gsm, sgmms, latent_posts=latent_posts, 
                                     latent_nsamples=5, params_nsamples=5)
    elbo.backward()
    optim.step()
    elbos.append(float(elbo))

In [10]:
fig = figure()
fig.line(range(len(elbos)), elbos)
show(fig)

In [11]:
fig1 = figure(title='True model')
for color, dataset, m_means, m_covs, m_weights in zip(colors, datasets, means, covs, weights):
    dataset = dataset.numpy()
    plotting.plot_normal(fig1, m_means[0], m_covs[0], alpha=.7 * m_weights[0], color=color)
    plotting.plot_normal(fig1, m_means[1], m_covs[1], alpha=.7 * m_weights[1], color=color)
    fig1.circle(dataset[:, 0], dataset[:, 1], alpha=.5, color=color)
    
fig2 = figure(title='Subspace GMM')
for gmm, dataset, color in zip(sgmms, datasets, colors):
    dataset = dataset.numpy()
    plotting.plot_gmm(fig2, gmm, alpha=.7, color=color)
    fig2.circle(dataset[:, 0], dataset[:, 1], color=color, alpha=.5)
    
fig3 = figure(title='Latent space')
mean, cov = gsm.latent_prior.mean.numpy(), gsm.latent_prior.cov.numpy()
plotting.plot_normal(fig3, mean, cov, alpha=.5, color='pink')
for mean, diag_cov, color in zip(latent_posts.params.mean, latent_posts.params.diag_cov, colors):
    mean = mean.detach().numpy()
    cov = diag_cov.detach().diag().numpy()
    plotting.plot_normal(fig3, mean, cov, alpha=.5, color=color)


show(gridplot([[fig1, fig2], [None, fig3]]))

In [12]:
# Type of covariance for the Subspace GMMs.
cov_type = 'full' # full/diagonal/isotropic
 
# Prior over the latent space.
mset = beer.NormalSet.create(
    torch.zeros(latent_dim), 
    torch.ones(latent_dim),
    size=2,
    cov_type=cov_type,
    noise_std=0.1,
).double()
gsm.latent_prior = beer.Mixture.create(mset)

In [13]:
fig1 = figure(title='True model')
for color, dataset, m_means, m_covs, m_weights in zip(colors, datasets, means, covs, weights):
    dataset = dataset.numpy()
    plotting.plot_normal(fig1, m_means[0], m_covs[0], alpha=.7 * m_weights[0], color=color)
    plotting.plot_normal(fig1, m_means[1], m_covs[1], alpha=.7 * m_weights[1], color=color)
    fig1.circle(dataset[:, 0], dataset[:, 1], alpha=.5, color=color)
    
fig2 = figure(title='Subspace GMM')
for gmm, dataset, color in zip(sgmms, datasets, colors):
    dataset = dataset.numpy()
    plotting.plot_gmm(fig2, gmm, alpha=.7, color=color)
    fig2.circle(dataset[:, 0], dataset[:, 1], color=color, alpha=.5)
    
fig3 = figure(title='Latent space')
plotting.plot_gmm(fig3, gsm.latent_prior, alpha=.5, color='pink')
for mean, diag_cov, color in zip(latent_posts.params.mean, latent_posts.params.diag_cov, colors):
    mean = mean.detach().numpy()
    cov = diag_cov.detach().diag().numpy()
    plotting.plot_normal(fig3, mean, cov, alpha=.5, color=color)


show(gridplot([[fig1, fig2], [None, fig3]]))

In [14]:
epochs = 5_000

# This function accumulate the statistics for the parameters
# of the subspace and update the parameters that are not
# part of the subspace.
def accumulate_stats(models, datasets, optims):
    for model, X, optim in zip(models, datasets, optims):
        optim.init_step()
        elbo = beer.evidence_lower_bound(model, X) 
        elbo.backward(std_params=False)
        optim.step()
        
# Prepare an optimzer for each SGMM. The optimizer
# will handle all parameters that are note included
# in the subspace.
sgmms_optims = []
for gmm in sgmms:
    mf_groups = []
    for group in gmm.mean_field_factorization():
        new_group = []
        for param in group:
            if isinstance(param, beer.ConjugateBayesianParameter):
                new_group.append(param)
        mf_groups.append(new_group)
    optim = beer.VariationalBayesOptimizer(mf_groups, lrate=1.)
    sgmms_optims.append(optim)
    
# We create a new optimizer for the GSM that will update the 
# latent prior as well.
optim = beer.VariationalBayesOptimizer(gsm.latent_prior.mean_field_factorization(), lrate=1., std_optim=std_optim)


elbos = []
for epoch in range(1, epochs + 1): 
    accumulate_stats(sgmms, datasets, sgmms_optims)
    optim.init_step()
    elbo = beer.evidence_lower_bound(gsm, sgmms, latent_posts=latent_posts, 
                                     latent_nsamples=5, params_nsamples=5)
    elbo.backward()
    optim.step()
    elbos.append(float(elbo))

In [15]:
fig = figure()
fig.line(range(len(elbos)), elbos)
show(fig)

In [16]:
fig1 = figure(title='True model')
for color, dataset, m_means, m_covs, m_weights in zip(colors, datasets, means, covs, weights):
    dataset = dataset.numpy()
    plotting.plot_normal(fig1, m_means[0], m_covs[0], alpha=.7 * m_weights[0], color=color)
    plotting.plot_normal(fig1, m_means[1], m_covs[1], alpha=.7 * m_weights[1], color=color)
    fig1.circle(dataset[:, 0], dataset[:, 1], alpha=.5, color=color)
    
fig2 = figure(title='Subspace GMM')
for gmm, dataset, color in zip(sgmms, datasets, colors):
    dataset = dataset.numpy()
    plotting.plot_gmm(fig2, gmm, alpha=.7, color=color)
    fig2.circle(dataset[:, 0], dataset[:, 1], color=color, alpha=.5)
    
fig3 = figure(title='Latent space')
plotting.plot_gmm(fig3, gsm.latent_prior, alpha=.5, color='pink')
for mean, diag_cov, color in zip(latent_posts.params.mean, latent_posts.params.diag_cov, colors):
    mean = mean.detach().numpy()
    cov = diag_cov.detach().diag().numpy()
    plotting.plot_normal(fig3, mean, cov, alpha=.5, color=color)


show(gridplot([[fig1, fig2], [None, fig3]]))

In [17]:
kl_div = beer.dists.kl_div
prior = gsm.affine_transform.bias.prior
posterior = gsm.affine_transform.bias.posterior
kl_div(posterior, prior)

tensor(-32.6252, dtype=torch.float64, grad_fn=<SubBackward0>)

In [18]:
posterior.params.diag_cov

tensor([1.6862e-04, 6.9750e-05, 5.1549e-02, 8.9986e-02, 5.1016e-04, 5.0290e-05,
        1.9059e-05, 7.8275e-02, 9.4411e-02, 2.8053e-04, 6.0130e-04],
       dtype=torch.float64, grad_fn=<ExpBackward>)

In [19]:
prior.params.mean, prior.params.diag_cov

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64),
 tensor([1000000.1919, 1000000.1919, 1000000.1919, 1000000.1919, 1000000.1919,
         1000000.1919, 1000000.1919, 1000000.1919, 1000000.1919, 1000000.1919,
         1000000.1919], dtype=torch.float64))

In [20]:
gsm.affine_transform.kl_div_posterior_prior()

tensor(304.0461, dtype=torch.float64, grad_fn=<AddBackward0>)

In [22]:
gsm.affine_transform.weights.value()

Parameter containing:
tensor([-1.0022e+01, -1.8028e-01,  2.3113e-05, -2.0903e-02, -2.7405e-03,
        -9.8374e+00, -3.3274e-01,  2.1472e-03, -8.5618e-04, -4.7210e-03,
        -4.3808e-03, -3.0953e-03, -3.3851e-03,  1.1670e+00, -2.9399e-01,
        -9.2456e-03,  5.8455e-04, -2.9402e-02,  1.1659e+00, -3.3671e-01,
         2.4972e-02,  5.9746e-05], dtype=torch.float64, requires_grad=True)